clear

echo -e "\t\e[1;107;31m¡Ingresaste al menu de ayuda!\e[0m"
echo ""
echo -e "\e[1;95m<limpiar>\e[0m"  
echo "Limpia los comandos que realizaste"
echo ""
echo -e "\e[1;95m<salir>\e[0m"  
echo "Al ejecutar este comando estaras cometiendo el segundo gran error de tu vida"
echo "saldrás de esta terminal :d"
echo ""  
echo -e "\e[1;95m<arbol>\e[0m" 
echo "Mostrara el directorio"
echo ""
echo -e "\e[1;95m<infosis>\e[0m" 
echo "Mostrara información del sistema"
echo ""
echo -e "\e[1;95m<fecha>\e[0m" 
echo "Si ya no sabes ni en que dia vives, yo te doy la fecha"
echo ""
echo -e "\e[1;95m<hora>\e[0m" 
echo "Te mostrare la hora"
echo ""
echo -e "\e[1;95m<buscar>\e[0m" 
echo "Permite buscar un archivo en un directorio"
echo ""
echo -e "\e[1;95m<creditos>\e[0m" 
echo "MOstrare la información de mis creadores <3"
echo ""
echo -e "\e[1;95m<gato>\e[0m" 
echo "Podras jugar gato"
echo ""
echo -e "\e[1;95m<ahorcado>\e[0m" 
echo "Podras jugar ahorcado"
echo ""
echo -e "\e[1;95m<prebeplayer>\e[0m" 
echo "Es un reproductor de musica"
